# This is a config for E2B sandbox template.
# You can use template ID (5q5q9v9kflakcmilhqxe) or template name (mobile-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("mobile-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("mobile-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('mobile-template')

team_id = "8bfae4ef-a1a9-4183-b2a5-4b59b8e19aec"
start_cmd = "cd /home/user/app && EXPO_NO_INTERACTIVE=1 EXPO_WEB_PORT=8081 PORT=8081 nohup bun run web > /tmp/expo.log 2>&1 & echo 'sandbox ready'"
dockerfile = "e2b.Dockerfile"
template_name = "mobile-template"
template_id = "5q5q9v9kflakcmilhqxe"
